framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\MessengerLockMiddleware
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/symfony/consumer-%env(CONSUMER_ID)%?auto_setup=true'
                retry_strategy:
                    delay: 60000
                    max_retries: 5
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\UnloadDataTo1CMessage: async
            App\Message\UploadReceivedFrom1CDataMessage: async
